### ISSUE TITLE
Firing - Executes multiple times per click

### ISSUE THREAD

**Issue by jakevolkman** [OSU-CS361-W17/group1_project3#16]
I've been testing the firing function for a while and found an interesting bug.

The program "fires" multiple times per click.
The number of times that it fires is equal to the number of ships that I've played on the board.

You can tell by the sound echo when the characters talk and the laser-gun goes off.
Placing 1 ship results in no echo.

Currently, when JavaScript calls Audio.play() too many times, Chrome actually crashes. So this redundancy is causing memory issues.

If anyone could figure out what's going on, it would at least improve the game experience.

**Comment by dmkato** [comment]
Yea, I noticed that every time you fire, it creates duplicates of each image that is being displayed, which after several fires, adds up to thousands of redundant images being loaded

**Comment by dmkato** [comment]
I'll look into it in a little bit

**Comment by daviandr** [comment]
Has this been fixed?

**Comment by dmkato** [comment]
Naw, but I'm working on it....

**Comment by jakevolkman** [comment]
Hey this is fixed?

**Comment by jakevolkman** [comment]
I think so
