### ISSUE TITLE
Display Civilian and Stealth Ships in Player Section

### ISSUE THREAD

**Issue by jakevolkman** [OSU-CS361-W17/group1_project3#17]
The Mr. Poopybutthole and Krombopulus Michael PNGs need to display over CivilianShips and StealthShips, respectively. This is a pretty easy JavaScript fix that just requires some copy and pasting, and maybe some HTML manipulation. It also completes Andrew's User Story.

**Comment by jakevolkman** [comment]
The ship status board still doesn't display the proper ship type.
I wonder if you could split the for loop in app.js to display each ship individually.
It's something to consider.

**Comment by daviandr** [comment]
That won't work. The html/css sets up the <div>shipStatus which covers table data <td> and table rows <tr>. So to change a single element in the css (which is where the morty heads display) would change the whole table data. So my problem is I have to manipulate the html and css and javascript.

**Comment by jakevolkman** [comment]
The only problem really is the div type "td" that shipstatus inherits in styles.css. What I can't figure out is how to have multiple "td" styles with different backgrounds images. 
I tried adding CSS to the JavaScript $ call but it didn't recognize the styles there.
If you wrote a JavaScript function that displayed a specific image based on a ship type and nested that in the for loop it should work.

**Comment by daviandr** [comment]
Exactly. I'm writing another function to .append <div>CIA/Civshipstatus. So the same thing but two more times. I don't think it will work but we can try.
