### ISSUE TITLE
Placing Ships - Request Failed

### ISSUE THREAD

**Issue by jakevolkman** [OSU-CS361-W17/group1_project3#7]
Hello all,

After merging Andrew's pull request for adding the ship class, the game now throws an error "request failed". This means that the JSON isn't being read correctly.

I'm going to assign everyone to this so they get an email about it. I'm looking into it now.

**Comment by dmkato** [comment]
I'm looking into this now

**Comment by jakevolkman** [comment]
Resolved by Daniel
